// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: logic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HistoryRequest is sent by a client to query conversation history.
type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`        // requester UID
	Peer          string                 `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`      // conversation peer UID
	Before        int64                  `protobuf:"varint,3,opt,name=before,proto3" json:"before,omitempty"` // fetch messages before this timestamp (ms), 0 = now
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`   // max number of messages, 0 = default (30)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_logic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *HistoryRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *HistoryRequest) GetBefore() int64 {
	if x != nil {
		return x.Before
	}
	return 0
}

func (x *HistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// HistoryResponse returns conversation history messages and a count.
type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Delivered     int32                  `protobuf:"varint,2,opt,name=delivered,proto3" json:"delivered,omitempty"` // number of messages actually returned
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_logic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *HistoryResponse) GetDelivered() int32 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

// UserRequest is sent to query a user by UID.
type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_logic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{2}
}

func (x *UserRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// UserResponse returns user information.
type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"` // false if user does not exist
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_logic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{3}
}

func (x *UserResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// SearchRequest is sent to perform a fulltext search on messages.
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                            // searching user (access control — must be participant)
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`                        // search terms
	Peer          string                 `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`                          // optional: scope to one conversation
	ChatType      int32                  `protobuf:"varint,4,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"` // optional filter: 0=all, 1=single, 2=group
	MsgType       int32                  `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`    // optional filter: 0=all
	Before        int64                  `protobuf:"varint,6,opt,name=before,proto3" json:"before,omitempty"`                     // optional: max timestamp (ms)
	After         int64                  `protobuf:"varint,7,opt,name=after,proto3" json:"after,omitempty"`                       // optional: min timestamp (ms)
	Limit         int32                  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`                       // max results, default 20, max 50
	Cursor        int64                  `protobuf:"varint,9,opt,name=cursor,proto3" json:"cursor,omitempty"`                     // keyset pagination: msg_id of last result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_logic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{4}
}

func (x *SearchRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *SearchRequest) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *SearchRequest) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *SearchRequest) GetBefore() int64 {
	if x != nil {
		return x.Before
	}
	return 0
}

func (x *SearchRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

// SearchResponse returns fulltext search results.
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                             // number of results in this page
	NextCursor    int64                  `protobuf:"varint,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // 0 = no more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_logic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SearchResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SearchResponse) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

// GroupInfo represents a chat group's metadata and member list.
type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // e.g. "g_123456"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // human-readable group name
	OwnerUid      string                 `protobuf:"bytes,3,opt,name=owner_uid,json=ownerUid,proto3" json:"owner_uid,omitempty"`     // creator/owner
	Members       []string               `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`                       // member UIDs
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_logic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{6}
}

func (x *GroupInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfo) GetOwnerUid() string {
	if x != nil {
		return x.OwnerUid
	}
	return ""
}

func (x *GroupInfo) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GroupInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// CreateGroupRequest is sent to create a new group.
type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OwnerUid      string                 `protobuf:"bytes,2,opt,name=owner_uid,json=ownerUid,proto3" json:"owner_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_logic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{7}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetOwnerUid() string {
	if x != nil {
		return x.OwnerUid
	}
	return ""
}

// CreateGroupResponse returns the newly created group.
type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *GroupInfo             `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty on success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_logic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{8}
}

func (x *CreateGroupResponse) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *CreateGroupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// JoinGroupRequest is sent to add a user to a group.
type JoinGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupRequest) Reset() {
	*x = JoinGroupRequest{}
	mi := &file_logic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupRequest) ProtoMessage() {}

func (x *JoinGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupRequest.ProtoReflect.Descriptor instead.
func (*JoinGroupRequest) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{9}
}

func (x *JoinGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *JoinGroupRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// JoinGroupResponse confirms membership.
type JoinGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // reason on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupResponse) Reset() {
	*x = JoinGroupResponse{}
	mi := &file_logic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupResponse) ProtoMessage() {}

func (x *JoinGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupResponse.ProtoReflect.Descriptor instead.
func (*JoinGroupResponse) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{10}
}

func (x *JoinGroupResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *JoinGroupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// LeaveGroupRequest is sent to remove a user from a group.
type LeaveGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupRequest) Reset() {
	*x = LeaveGroupRequest{}
	mi := &file_logic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupRequest) ProtoMessage() {}

func (x *LeaveGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupRequest.ProtoReflect.Descriptor instead.
func (*LeaveGroupRequest) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{11}
}

func (x *LeaveGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *LeaveGroupRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// LeaveGroupResponse confirms departure.
type LeaveGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"` // true if group was deleted (last member left)
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      // reason on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupResponse) Reset() {
	*x = LeaveGroupResponse{}
	mi := &file_logic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupResponse) ProtoMessage() {}

func (x *LeaveGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupResponse.ProtoReflect.Descriptor instead.
func (*LeaveGroupResponse) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{12}
}

func (x *LeaveGroupResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LeaveGroupResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *LeaveGroupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetGroupRequest is sent to query group details.
type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_logic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{13}
}

func (x *GetGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// GetGroupResponse returns group info if found.
type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *GroupInfo             `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_logic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{14}
}

func (x *GetGroupResponse) GetGroup() *GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GetGroupResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// ListGroupsRequest is sent to list groups for a user.
type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_logic_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{15}
}

func (x *ListGroupsRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// ListGroupsResponse returns the groups the user belongs to.
type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*GroupInfo           `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_logic_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{16}
}

func (x *ListGroupsResponse) GetGroups() []*GroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

// UnreadCount represents the number of unread messages for a conversation.
type UnreadCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`    // conversation peer UID or group ID
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // number of unread messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadCount) Reset() {
	*x = UnreadCount{}
	mi := &file_logic_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadCount) ProtoMessage() {}

func (x *UnreadCount) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadCount.ProtoReflect.Descriptor instead.
func (*UnreadCount) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{17}
}

func (x *UnreadCount) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *UnreadCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// IncrementUnreadRequest is sent to increment the unread count for a conversation.
type IncrementUnreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`   // user whose unread count to increment (receiver)
	Peer          string                 `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"` // sender UID or group ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementUnreadRequest) Reset() {
	*x = IncrementUnreadRequest{}
	mi := &file_logic_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementUnreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementUnreadRequest) ProtoMessage() {}

func (x *IncrementUnreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementUnreadRequest.ProtoReflect.Descriptor instead.
func (*IncrementUnreadRequest) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{18}
}

func (x *IncrementUnreadRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *IncrementUnreadRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

// IncrementUnreadResponse returns the new count.
type IncrementUnreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewCount      int64                  `protobuf:"varint,1,opt,name=new_count,json=newCount,proto3" json:"new_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementUnreadResponse) Reset() {
	*x = IncrementUnreadResponse{}
	mi := &file_logic_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementUnreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementUnreadResponse) ProtoMessage() {}

func (x *IncrementUnreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementUnreadResponse.ProtoReflect.Descriptor instead.
func (*IncrementUnreadResponse) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{19}
}

func (x *IncrementUnreadResponse) GetNewCount() int64 {
	if x != nil {
		return x.NewCount
	}
	return 0
}

// MarkReadRequest is sent to mark a conversation as read.
type MarkReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reader        string                 `protobuf:"bytes,1,opt,name=reader,proto3" json:"reader,omitempty"` // user who read the messages
	Peer          string                 `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`     // conversation peer or group
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_logic_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{20}
}

func (x *MarkReadRequest) GetReader() string {
	if x != nil {
		return x.Reader
	}
	return ""
}

func (x *MarkReadRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

// MarkReadResponse confirms the operation.
type MarkReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadResponse) Reset() {
	*x = MarkReadResponse{}
	mi := &file_logic_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadResponse) ProtoMessage() {}

func (x *MarkReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadResponse.ProtoReflect.Descriptor instead.
func (*MarkReadResponse) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{21}
}

func (x *MarkReadResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// GetUnreadCountsRequest is sent to fetch all unread counts for a user.
type GetUnreadCountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountsRequest) Reset() {
	*x = GetUnreadCountsRequest{}
	mi := &file_logic_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountsRequest) ProtoMessage() {}

func (x *GetUnreadCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountsRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountsRequest) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{22}
}

func (x *GetUnreadCountsRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// GetUnreadCountsResponse returns per-conversation unread counts.
type GetUnreadCountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        []*UnreadCount         `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountsResponse) Reset() {
	*x = GetUnreadCountsResponse{}
	mi := &file_logic_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountsResponse) ProtoMessage() {}

func (x *GetUnreadCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountsResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountsResponse) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{23}
}

func (x *GetUnreadCountsResponse) GetCounts() []*UnreadCount {
	if x != nil {
		return x.Counts
	}
	return nil
}

var File_logic_proto protoreflect.FileDescriptor

const file_logic_proto_rawDesc = "" +
	"\n" +
	"\vlogic.proto\x12\x02im\x1a\rmessage.proto\"d\n" +
	"\x0eHistoryRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04peer\x18\x02 \x01(\tR\x04peer\x12\x16\n" +
	"\x06before\x18\x03 \x01(\x03R\x06before\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"X\n" +
	"\x0fHistoryResponse\x12'\n" +
	"\bmessages\x18\x01 \x03(\v2\v.im.MessageR\bmessages\x12\x1c\n" +
	"\tdelivered\x18\x02 \x01(\x05R\tdelivered\"\x1f\n" +
	"\vUserRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"R\n" +
	"\fUserResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"\xdf\x01\n" +
	"\rSearchRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x12\n" +
	"\x04peer\x18\x03 \x01(\tR\x04peer\x12\x1b\n" +
	"\tchat_type\x18\x04 \x01(\x05R\bchatType\x12\x19\n" +
	"\bmsg_type\x18\x05 \x01(\x05R\amsgType\x12\x16\n" +
	"\x06before\x18\x06 \x01(\x03R\x06before\x12\x14\n" +
	"\x05after\x18\a \x01(\x03R\x05after\x12\x14\n" +
	"\x05limit\x18\b \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\t \x01(\x03R\x06cursor\"p\n" +
	"\x0eSearchResponse\x12'\n" +
	"\bmessages\x18\x01 \x03(\v2\v.im.MessageR\bmessages\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\x03R\n" +
	"nextCursor\"\x85\x01\n" +
	"\tGroupInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\towner_uid\x18\x03 \x01(\tR\bownerUid\x12\x18\n" +
	"\amembers\x18\x04 \x03(\tR\amembers\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"E\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\towner_uid\x18\x02 \x01(\tR\bownerUid\"P\n" +
	"\x13CreateGroupResponse\x12#\n" +
	"\x05group\x18\x01 \x01(\v2\r.im.GroupInfoR\x05group\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"?\n" +
	"\x10JoinGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\"9\n" +
	"\x11JoinGroupResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"@\n" +
	"\x11LeaveGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\"T\n" +
	"\x12LeaveGroupResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\",\n" +
	"\x0fGetGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"M\n" +
	"\x10GetGroupResponse\x12#\n" +
	"\x05group\x18\x01 \x01(\v2\r.im.GroupInfoR\x05group\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"%\n" +
	"\x11ListGroupsRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\";\n" +
	"\x12ListGroupsResponse\x12%\n" +
	"\x06groups\x18\x01 \x03(\v2\r.im.GroupInfoR\x06groups\"7\n" +
	"\vUnreadCount\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\">\n" +
	"\x16IncrementUnreadRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04peer\x18\x02 \x01(\tR\x04peer\"6\n" +
	"\x17IncrementUnreadResponse\x12\x1b\n" +
	"\tnew_count\x18\x01 \x01(\x03R\bnewCount\"=\n" +
	"\x0fMarkReadRequest\x12\x16\n" +
	"\x06reader\x18\x01 \x01(\tR\x06reader\x12\x12\n" +
	"\x04peer\x18\x02 \x01(\tR\x04peer\"\"\n" +
	"\x10MarkReadResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"*\n" +
	"\x16GetUnreadCountsRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"B\n" +
	"\x17GetUnreadCountsResponse\x12'\n" +
	"\x06counts\x18\x01 \x03(\v2\x0f.im.UnreadCountR\x06counts2\xa1\x05\n" +
	"\x05Logic\x127\n" +
	"\fQueryHistory\x12\x12.im.HistoryRequest\x1a\x13.im.HistoryResponse\x12,\n" +
	"\aGetUser\x12\x0f.im.UserRequest\x1a\x10.im.UserResponse\x127\n" +
	"\x0eSearchMessages\x12\x11.im.SearchRequest\x1a\x12.im.SearchResponse\x12>\n" +
	"\vCreateGroup\x12\x16.im.CreateGroupRequest\x1a\x17.im.CreateGroupResponse\x128\n" +
	"\tJoinGroup\x12\x14.im.JoinGroupRequest\x1a\x15.im.JoinGroupResponse\x12;\n" +
	"\n" +
	"LeaveGroup\x12\x15.im.LeaveGroupRequest\x1a\x16.im.LeaveGroupResponse\x125\n" +
	"\bGetGroup\x12\x13.im.GetGroupRequest\x1a\x14.im.GetGroupResponse\x12;\n" +
	"\n" +
	"ListGroups\x12\x15.im.ListGroupsRequest\x1a\x16.im.ListGroupsResponse\x12J\n" +
	"\x0fIncrementUnread\x12\x1a.im.IncrementUnreadRequest\x1a\x1b.im.IncrementUnreadResponse\x125\n" +
	"\bMarkRead\x12\x13.im.MarkReadRequest\x1a\x14.im.MarkReadResponse\x12J\n" +
	"\x0fGetUnreadCounts\x12\x1a.im.GetUnreadCountsRequest\x1a\x1b.im.GetUnreadCountsResponseB\x1fZ\x1dgithub.com/im/api/proto;protob\x06proto3"

var (
	file_logic_proto_rawDescOnce sync.Once
	file_logic_proto_rawDescData []byte
)

func file_logic_proto_rawDescGZIP() []byte {
	file_logic_proto_rawDescOnce.Do(func() {
		file_logic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logic_proto_rawDesc), len(file_logic_proto_rawDesc)))
	})
	return file_logic_proto_rawDescData
}

var file_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_logic_proto_goTypes = []any{
	(*HistoryRequest)(nil),          // 0: im.HistoryRequest
	(*HistoryResponse)(nil),         // 1: im.HistoryResponse
	(*UserRequest)(nil),             // 2: im.UserRequest
	(*UserResponse)(nil),            // 3: im.UserResponse
	(*SearchRequest)(nil),           // 4: im.SearchRequest
	(*SearchResponse)(nil),          // 5: im.SearchResponse
	(*GroupInfo)(nil),               // 6: im.GroupInfo
	(*CreateGroupRequest)(nil),      // 7: im.CreateGroupRequest
	(*CreateGroupResponse)(nil),     // 8: im.CreateGroupResponse
	(*JoinGroupRequest)(nil),        // 9: im.JoinGroupRequest
	(*JoinGroupResponse)(nil),       // 10: im.JoinGroupResponse
	(*LeaveGroupRequest)(nil),       // 11: im.LeaveGroupRequest
	(*LeaveGroupResponse)(nil),      // 12: im.LeaveGroupResponse
	(*GetGroupRequest)(nil),         // 13: im.GetGroupRequest
	(*GetGroupResponse)(nil),        // 14: im.GetGroupResponse
	(*ListGroupsRequest)(nil),       // 15: im.ListGroupsRequest
	(*ListGroupsResponse)(nil),      // 16: im.ListGroupsResponse
	(*UnreadCount)(nil),             // 17: im.UnreadCount
	(*IncrementUnreadRequest)(nil),  // 18: im.IncrementUnreadRequest
	(*IncrementUnreadResponse)(nil), // 19: im.IncrementUnreadResponse
	(*MarkReadRequest)(nil),         // 20: im.MarkReadRequest
	(*MarkReadResponse)(nil),        // 21: im.MarkReadResponse
	(*GetUnreadCountsRequest)(nil),  // 22: im.GetUnreadCountsRequest
	(*GetUnreadCountsResponse)(nil), // 23: im.GetUnreadCountsResponse
	(*Message)(nil),                 // 24: im.Message
}
var file_logic_proto_depIdxs = []int32{
	24, // 0: im.HistoryResponse.messages:type_name -> im.Message
	24, // 1: im.SearchResponse.messages:type_name -> im.Message
	6,  // 2: im.CreateGroupResponse.group:type_name -> im.GroupInfo
	6,  // 3: im.GetGroupResponse.group:type_name -> im.GroupInfo
	6,  // 4: im.ListGroupsResponse.groups:type_name -> im.GroupInfo
	17, // 5: im.GetUnreadCountsResponse.counts:type_name -> im.UnreadCount
	0,  // 6: im.Logic.QueryHistory:input_type -> im.HistoryRequest
	2,  // 7: im.Logic.GetUser:input_type -> im.UserRequest
	4,  // 8: im.Logic.SearchMessages:input_type -> im.SearchRequest
	7,  // 9: im.Logic.CreateGroup:input_type -> im.CreateGroupRequest
	9,  // 10: im.Logic.JoinGroup:input_type -> im.JoinGroupRequest
	11, // 11: im.Logic.LeaveGroup:input_type -> im.LeaveGroupRequest
	13, // 12: im.Logic.GetGroup:input_type -> im.GetGroupRequest
	15, // 13: im.Logic.ListGroups:input_type -> im.ListGroupsRequest
	18, // 14: im.Logic.IncrementUnread:input_type -> im.IncrementUnreadRequest
	20, // 15: im.Logic.MarkRead:input_type -> im.MarkReadRequest
	22, // 16: im.Logic.GetUnreadCounts:input_type -> im.GetUnreadCountsRequest
	1,  // 17: im.Logic.QueryHistory:output_type -> im.HistoryResponse
	3,  // 18: im.Logic.GetUser:output_type -> im.UserResponse
	5,  // 19: im.Logic.SearchMessages:output_type -> im.SearchResponse
	8,  // 20: im.Logic.CreateGroup:output_type -> im.CreateGroupResponse
	10, // 21: im.Logic.JoinGroup:output_type -> im.JoinGroupResponse
	12, // 22: im.Logic.LeaveGroup:output_type -> im.LeaveGroupResponse
	14, // 23: im.Logic.GetGroup:output_type -> im.GetGroupResponse
	16, // 24: im.Logic.ListGroups:output_type -> im.ListGroupsResponse
	19, // 25: im.Logic.IncrementUnread:output_type -> im.IncrementUnreadResponse
	21, // 26: im.Logic.MarkRead:output_type -> im.MarkReadResponse
	23, // 27: im.Logic.GetUnreadCounts:output_type -> im.GetUnreadCountsResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_logic_proto_init() }
func file_logic_proto_init() {
	if File_logic_proto != nil {
		return
	}
	file_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logic_proto_rawDesc), len(file_logic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logic_proto_goTypes,
		DependencyIndexes: file_logic_proto_depIdxs,
		MessageInfos:      file_logic_proto_msgTypes,
	}.Build()
	File_logic_proto = out.File
	file_logic_proto_goTypes = nil
	file_logic_proto_depIdxs = nil
}
